apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
spec:
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  type: NodePort